# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskManager
pod 'Texture'
pod 'Firebase/Firestore'
pod 'XLForm', '~> 4.1'
pod 'CouchbaseLite', '~> 2.7.0'
end
